# Generated by Django 4.2.1 on 2023-07-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=128, verbose_name="텍스트리뷰")),
                ("light", models.IntegerField()),
                ("people", models.IntegerField()),
                ("clear", models.IntegerField()),
            ],
        ),
    ]
