# Generated by Django 4.2.1 on 2023-07-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="clear",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="light",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="people",
            field=models.IntegerField(null=True),
        ),
    ]
