# Generated by Django 4.2.1 on 2023-07-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0002_alter_review_clear_alter_review_light_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default=True, max_length=1208, verbose_name="주소이름"),
        ),
    ]
