# Generated by Django 4.2.1 on 2023-07-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0003_review_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bowery153_171",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_name", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=20)),
                ("user_avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_light", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_people", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_clear", models.DecimalField(decimal_places=1, max_digits=2)),
                ("date", models.CharField(max_length=30)),
                ("content", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Bowery181",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_name", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=20)),
                ("user_avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_light", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_people", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_clear", models.DecimalField(decimal_places=1, max_digits=2)),
                ("date", models.CharField(max_length=30)),
                ("content", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Bowery68",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_name", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=20)),
                ("user_avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_light", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_people", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_clear", models.DecimalField(decimal_places=1, max_digits=2)),
                ("date", models.CharField(max_length=30)),
                ("content", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Broome334",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_name", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=20)),
                ("user_avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_light", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_people", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_clear", models.DecimalField(decimal_places=1, max_digits=2)),
                ("date", models.CharField(max_length=30)),
                ("content", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Chrystie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_name", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=20)),
                ("user_avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_light", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_people", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_clear", models.DecimalField(decimal_places=1, max_digits=2)),
                ("date", models.CharField(max_length=30)),
                ("content", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Kenmare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_name", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=20)),
                ("user_avg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_light", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_people", models.DecimalField(decimal_places=1, max_digits=2)),
                ("user_clear", models.DecimalField(decimal_places=1, max_digits=2)),
                ("date", models.CharField(max_length=30)),
                ("content", models.TextField(max_length=200)),
            ],
        ),
    ]
