# Generated by Django 4.2.1 on 2023-07-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0004_bowery153_171_bowery181_bowery68_broome334_chrystie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bowery153_171",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="bowery181",
            name="content",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="bowery68",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="broome334",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="chrystie",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="kenmare",
            name="content",
            field=models.TextField(max_length=500),
        ),
    ]
