# Generated by Django 4.2.1 on 2023-07-14 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0005_alter_bowery153_171_content_alter_bowery181_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="작성일"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bowery153_171",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="bowery181",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="bowery68",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="broome334",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="chrystie",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="kenmare",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
    ]
